# Generated by Django 4.0.3 on 2022-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogowner', '0002_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogowner',
            name='dog_picture_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
