# Generated by Django 4.0.3 on 2022-04-07 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daycare', '0002_test_data'),
        ('dogowner', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('O'), ('D')], max_length=1)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('daycare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.daycare')),
                ('dogowner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogowner.dogowner')),
            ],
        ),
    ]
