# Generated by Django 4.0.3 on 2022-03-30 19:27

from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('daycare', '0002_test_data'),
        ('dogowner', '0002_test_data'),
    ]

    def generate_data(apps, schema_editor):
        from message.models import Message
        from daycare.models import DayCare
        from dogowner.models import DogOwner

        test_data = [
           ('O', 1, 1, 'First message'),
           ('D', 2, 2, 'Second message'),
           ('O', 1, 1, 'Reply to first message'),
           ('D', 2, 2, 'Reply to second message'),
        ]

        with transaction.atomic():
            for author, daycare_id, dogowner_id, text in test_data:
                Message.create(author=author,
                               dogowner_id=DogOwner.objects.get(pk=dogowner_id),
                               daycare_id=DayCare.objects.get(pk=daycare_id),
                               text=text).save()

    operations = [
        migrations.RunPython(generate_data),
    ]
