# Generated by Django 4.0.3 on 2022-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('capacity', models.IntegerField()),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('adrress', models.CharField(max_length=100)),
            ],
        ),
    ]
