# Generated by Django 4.0.3 on 2022-04-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_test_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
    ]
