# Generated by Django 4.0.3 on 2022-04-27 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0005_image_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='area',
            field=models.CharField(blank=True, choices=[('N', 'NORTH'), ('S', 'SOUTH'), ('C', 'CENTER')],
                                   max_length=20, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
