# Generated by Django 4.0.3 on 2022-04-11 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daycare', '0001_initial'),
        ('dogowner', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                           django.core.validators.MaxValueValidator(5)])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('daycare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to='daycare.daycare')),
                ('dogowner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='dogowner.dogowner')),
            ],
        ),
    ]
