# Generated by Django 4.0.3 on 2022-04-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogowner', '0001_initial'),
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(auto_now=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('price_per_day', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'),
                                                     ('A', 'Approved'),
                                                     ('C', 'Canceled'),
                                                     ('F', 'Finished'),
                                                     ('O', 'On Going')],
                                            default='P',
                                            max_length=1)),
                ('daycare_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to='daycare.daycare')),
                ('dog_owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='dogowner.dogowner')),
            ],
        ),
    ]
